# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4bd145789f3a6d40a6a9179c8949c3481ce71bf4233784e62037b8bb38ca44c1e72fa9a22d69e81adb5dfc2d650efe8dec9d82ba23cc8233f87b36e6abcff0c

test:
  secret_key_base: 43d4f32ee574cbb97914d35b84b92dd993e50a4a46652feb08c506dd55b885d0c6285a323882528ff4ff4f27c2eb5fb5b01159e7df401e41d305dfa9ada2e44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
